#NAME: Henry MacArthur
#EMAIL: HenryMac16@gmail.com
#ID: 705096169
default:
	gcc -lmraa -Wall -Wextra lab4b.c -o lab4b -lm
clean:
	rm -rf *.tar.gz lab4b
dist:
	tar -vczf lab4b-705096169.tar.gz lab4b.c SmokeTest.sh README Makefile
check:
	./SmokeTest.sh
