# NAME: Derek Vance, Henry MacArthur
# EMAIL: dvance@g.ucla.edu, henrymac16@gmail.com
# ID: 604970765, 705096169

default:
	gcc -o lab3a lab3a.c -Wall -Wextra

dist: 
	tar -czvf lab3a-604970765.tar.gz lab3a.c README Makefile ext2_fs.h

clean:
	rm -f lab3a 
	rm -f lab3a-604970765.tar.gz